# If a player is offline more than this number of hours at server start, his chunk loaders won't be loaded
MaxHoursOffline: 72

# Default amount of chunks for all players
DefaultChunksAmount:
  AlwaysOn: 0
  OnlineOnly: 0
  
# Max amount of chunks for each player
MaxChunksAmount:
  AlwaysOn: 250
  OnlineOnly: 250
  
# Data Store to use, XML or MySQL, but extensions can add custom data stores
DataStore: XML

#ModRealms
ServerName: server

# Configuration for MySQL Data Store
MySQL:
  Hostname: localhost
  Username: BetterChunkLoader
  Password: BetterPassword
  Database: BetterChunkLoader
  